language: c
sudo: required
before_script:
- chmod +x ./bin/cibuild
before_install:
- openssl aes-256-cbc -K $encrypted_957066c6439f_key -iv $encrypted_957066c6439f_iv
  -in id_rsa.enc -out ~\/.ssh/id_rsa -d
- apt-get update
- apt-get upgrade
- apt-get install pandoc
script: ./bin/build
branches:
  only:
  - gh-pages
  - /pages-(.*)/
  - /blog-(.*)/
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
